version: "3"

services:
    guitars-db:
        image: postgres:13-alpine
        restart: always
        volumes:
            - guitars-db:/var/lib/postgresql/
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DBNAME}
        networks:
            - guitars-db

    build:
        build: ./
        environment:
            - SERVER_URL

    guitars-server:
        depends_on:
            - build
            - guitars-db
        build: ./packages/guitars-server/
        networks:
            - guitars-db
            
        ports:
            - 5000:5000
        environment:
            - DB_HOST
            - DB_PASSWORD
            - DB_USERNAME
            - DB_DBNAME
            - SERVER_PORT
            - SERVER_URL

    guitars-client:
        depends_on:
            - build
            - guitars-server
        build: ./packages/guitars-client/
        networks:
            - guitars-server
        ports:
            - 3000:3000
        environment:
            - SERVER_URL

volumes:
    guitars-db:

networks:
    guitars-db:
    guitars-server: